name: Build Modpack

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload modpack.zip
      uses: actions/upload-artifact@v4
      with:
        name: modpack
        path: modpack.zip

    - name: Upload modpack files
      uses: actions/upload-artifact@v4
      with:
        name: modpack
        path: |
          overrides/**
          changelogs/**
          README.md
          manifest.json
          CHANGELOG.md
          
